### ISSUE TITLE
One more tip

### ISSUE THREAD

**Issue by MaxGraey** [HdrHistogram/HdrHistogramJS#23]
Btw AssemblyScript has builtin bit methods like `popcnt`, `clz` and `ctz`, so you could optimize your `bitCount` and `bitCount32` to `popcnt<u64>(n)` and `popcnt<u32>(n)` here:

https://github.com/HdrHistogram/HdrHistogramJS/blob/master/assembly/packedarray/bitcount.ts

**Comment by MaxGraey** [comment]
also if you don't want to pass function as parameter to other function better always use "function declaration" instead "function expression":
`export const bitCount = (n: u64): u8 => { ...`  ->   `export function bitCount(n: u64): u8 { ...`

**Comment by alexvictoor** [comment]
Thank you so much @MaxGraey !
Did know how I have missed popcnt...
Out of curiosity why "function declaration" is better than "function expression"?

**Comment by MaxGraey** [comment]
> Out of curiosity why "function declaration" is better than "function expression"?

All function expressions interpret as indirect function and store in reference table. Usually binaryen optimize such cases via directize call sites, but this not always happening so better avoid expressions until it really necessary

**Comment by alexvictoor** [comment]
Thanks!
