### ISSUE TITLE
Recreating a histogram from the percentile distribution output provides same percentiles, but different summary (mean, max, stddev)

### ISSUE THREAD

**Issue by GavinRay97** [HdrHistogram/HdrHistogramJS#24]
I have a scenario where I'm using HDRHistogram and it's `.toJSON()` as a standard interface between several different tool outputs.

One of them is `wrk2`, which provides it's own stat output object, and HDRHistogram percentile distribution at the end of the run, but it's more useful to reverse that and rebuild the actual `Histogram` object in Node so that I can call `toJSON()` (or whatever else) on it and have a standardized class/object.

**The conundrum is this:** 

If you parse the output of `hdr.outputPercentileDistribution()`, and use that to rebuild the initial histogram, the final result is slightly different.

![image](https://user-images.githubusercontent.com/26604994/88860472-cf040400-d1c9-11ea-94a5-6127eb9ae542.png)
https://www.diffchecker.com/8dwIT5h3

Demo of the issue here (just open and it should print to console pane on righthand side):
https://codesandbox.io/s/frosty-night-0noxy?file=/src/index.ts:5627-6019

```ts
interface ParsedHDRHistogramSummary {
  buckets: number
  count: number
  max: number
  mean: number
  stddev: number
  sub_buckets: number
}

interface ParsedHDRHistogramValue {
  value: number
  percentile: number
  total_count: number
  of_one_percentile: number
}

interface ParsedHDRHistogram {
  summary: ParsedHDRHistogramSummary
  values: ParsedHDRHistogramValue[]
}

function convertPropertiesTo(type, obj) {
  for (let k in obj) obj[k] = type(obj[k])
  return obj
}

function parseHdrHistogram(text: string): ParsedHDRHistogram {
  let valuesRegex = new RegExp(
    /(?<value>\d+\.?\d*)[ ]+(?<percentile>\d+\.?\d*)[ ]+(?<total_count>\d+\.?\d*)([ ]+(?<of_one_percentile>\d+\.?\d*))?/g
  )

  // prettier-ignore
  let summaryRegex = new RegExp(
    /#\[Mean    =       (?<mean>\d+\.?\d*), StdDeviation   =        (?<stddev>\d+\.?\d*)]/.source + "\n" +
    /#\[Max     =       (?<max>\d+\.?\d*), Total count    =         (?<count>\d+\.?\d*)]/.source + "\n" +
    /#\[Buckets =            (?<buckets>\d+\.?\d*), SubBuckets     =         (?<sub_buckets>\d+\.?\d*)]/.source,
    'g'
  )

  // prettier-ignore
  const values: ParsedHDRHistogramValue[] = [...text.matchAll(valuesRegex)]
    .flatMap((it) => convertPropertiesTo(Number, it.groups as any))

  const summary: ParsedHDRHistogramSummary = [...text.matchAll(summaryRegex)]
    .flatMap((it) => convertPropertiesTo(Number, it.groups as any))
    .pop()

  return { summary, values }
}

// Calculates the amount of values per point in the percentile output 
function calculateHistogramIntervalCounts(values: ParsedHDRHistogramValue[]) {
  type HistogramPoint = { amount: number; value: number }
  let res: HistogramPoint[] = []

  let lastCount = 0
  for (let entry of values) {
    let amount = entry.total_count - lastCount
    let value = Math.round(entry.value)
    res.push({ amount, value })
    lastCount = entry.total_count
  }

  return res
}

function reconstructHdrHistogramFromParsed(parsedHistogram: ParsedHDRHistogram) {
  const histogram = hdr.build()
  const intervals = calculateHistogramIntervalCounts(parsedHistogram.values)
  for (let entry of intervals)
    histogram.recordValueWithCount(entry.value, entry.amount)
  return histogram
}

const reconstructHdrHistogramFromText = (text: string) =>
  reconstructHdrHistogramFromParsed(parseHdrHistogram(text))
```

**Comment by alexvictoor** [comment]
Hello @GavinRay97 !
If you need to serialize and then deserialize an histogram, I highly recommend to use [encoding/decoding features](https://github.com/HdrHistogram/HdrHistogramJS#encode--decode).
Instead of outputPercentileDistribution() use **hdr.encodeIntoBase64String()** and  **hdr. decodeFromCompressedBase64()**
This should work better than parsing the percentile distribution.

**Comment by GavinRay97** [comment]
@alexvictoor But if the input is coming as `stdout` output from an external program and it doesn't expose the HDRHistogram library I am not able to use those methods :frowning: 

I have to parse the terminal output of `wrk2`. Which is okay, so I parse it, and then build the histogram again using the values from the percentile distribution, and all the numbers are correct except for `mean`, `max`, and `stdDeviation`.

What should I do if I cannot control the format of tools which give the percentile distribution and it's only text? Can I correct the calculation so it matches?

Sorry if this is a silly question, I know it's a farfetched scenario but it's really throwing me for a loop that the histograms have the same data points but different aggregate values after I parse + reassemble :sweat_smile:

**Comment by alexvictoor** [comment]
Ok @GavinRay97 I will take a look at this and get back to you quickly

**Comment by alexvictoor** [comment]
After thinking a little bit about how the output is built, this is not surprising that after parsing you get a good distribution and a not so good summary. This is because in the output you have less information than in the whole histogram. If you take a look at this code fragment :
```
const h = build();
for (let index = 0; index < 500; index++) {
      h.recordValue(index);
}

console.log(h.outputPercentileDistribution());
```
You get the following output:
```
  Value     Percentile TotalCount 1/(1-Percentile)
   
  0.000 0.000000000000          1           1.00
 49.000 0.100000000000         50           1.11
 99.000 0.200000000000        100           1.25

...

496.000 0.993750000000        497         160.00
497.000 0.994531250000        498         182.86
497.000 0.995312500000        498         213.33
498.000 0.996093750000        499         256.00
498.000 0.996484375000        499         284.44
498.000 0.996875000000        499         320.00
498.000 0.997265625000        499         365.71
498.000 0.997656250000        499         426.67
499.000 0.998046875000        500         512.00
499.000 1.000000000000        500
[Info]        #[Mean    =      249.500, StdDeviation   =      144.337]
[Info]        #[Max     =      499.000, Total count    =          500]
[Info]        #[Buckets =            1, SubBuckets     =         2048]
```

Looking at this output there is no way to say that there was one record for each value between 0 and 500. If you take a look at the first lines, you can say that there were 50 records for value 49 or less, that is it...

Since HdrHistogram_C has a [hdr_encode_compressed()](https://github.com/HdrHistogram/HdrHistogram_c/blob/1a823d9666b9a5262fbbf527ac63b574828bf67d/src/hdr_histogram_log.c#L165) function, I guess a solution would be to ask @giltene if it would be a good think to add an option in wrk2 to get the results as a base64 compressed string.

**Comment by GavinRay97** [comment]
@alexvictoor Ah okay, that makes sense that there's a loss of information density so the summaries are a bit off.
The original input can be +10,000's/100,000's of points, but to reconstruct it you only get ~50(?) data points.

> Since HdrHistogram_C has a hdr_encode_compressed() function, I guess a solution would be to ask @giltene if it would be a good think to add an option in wrk2 to get the results as a base64 compressed string.

Yeah that's a great idea, at least for `wrk` it would work :smiley: 

Genuinely appreciate the time you've taken to respond and the great work on this library.

**Comment by alexvictoor** [comment]
Thanks for your kind words!
I guess the `1/(1-percentile)` is useful to plot the data, it will be used as the 'x' in the graph. This is not obvious looking at the code but if you want you can take a look [here](https://github.com/HdrHistogram/HdrHistogramJSDemo/blob/gh-pages/plotFiles.html#L165)

**Comment by GavinRay97** [comment]
Ah alright, thanks!

I suppose can close this issue now, not possible to resolve it without magically having more input data.
Thanks again :+1:
