### ISSUE TITLE
Error when upgrading to Angular 12

### ISSUE THREAD

**Issue by drowhunter** [HdrHistogram/HdrHistogramJS#38]
I have a project that when updated to Angular 12 I suddenly get an error such as 

```node_modules/hd-histogram-js/src/packedarray/PackedArray.spec.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig at node_modules/@ngtools/webpack/rsc/ivy/loader.js:59:26```

**Comment by drowhunter** [comment]
Sorry Infigured this out.  It was due to the test.ts fike being moved to the root of the project.  In angular 11 it worked but in 12 it ends up including thw entire node_modules folder

**Comment by joannaLa** [comment]
@drowhunter Please tell me how you resolve your issue. I have the same error. Did you move your test.ts something else or I should add some property to angular tsconfig file?

**Comment by alexvictoor** [comment]
@drowhunter <https://github.com/drowhunter> I do not use angular  so let me
know if we should add an angular section in the doc
