### ISSUE TITLE
hdr-histogram-js pkg is not present in the npmjs auto suggest

### ISSUE THREAD

**Issue by ThierryAbalea** [HdrHistogram/HdrHistogramJS#4]
hdr-histogram-js package is not present in the npmjs auto suggest. Even if you type the full package name, i.e. "hdr-histogram-js", it does not work. But if you press the Enter key, you can find it. I think it can hurt the discovery of this library.

The problem does not exist on yarnpkg.com

**Comment by alexvictoor** [comment]
Fixed now
