### ISSUE TITLE
Library Vulnerabilities 

### ISSUE THREAD

**Issue by amargar80** [HdrHistogram/HdrHistogramJS#41]
In a angular project I used the 'angular-devkit/build-angular' package which has dependency with 'piscina' and 'piscina' depends on 'hdr-histogram-js'.
After whitesource execution the 'https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js'  on node_modules\hdr-histogram-js\benchmark\results\data-access.chart.html page is out of date and this cause the report to fail.

![image](https://user-images.githubusercontent.com/96264993/146449645-9fef2498-40b1-4bfb-aa24-1889abbfb818.png)

**Comment by alexvictoor** [comment]
Thanks for reporting this issue. A new release of HdrHistogramJS which should fix this issue will be out pretty soon.

**Comment by alexvictoor** [comment]
@amargar80 is this issue fixed on your side with version 2.0.2?
