### ISSUE TITLE
Travis CI link on npmjs & yarnpkg.com is broken

### ISSUE THREAD

**Issue by ThierryAbalea** [HdrHistogram/HdrHistogramJS#5]
The Travis CI link in the README presented on npmjs & yarnpkg.com is broken. The current one is
https://travis-ci.org/alexvictoor/HdrHistogramJS
Expected one:
https://travis-ci.org/HdrHistogram/HdrHistogramJS

There are referencing the latest version of the package: 1.0.0-beta.3

So I supposed the link in the README was modified after the release and need to be re-submitted to be fix.

**Comment by alexvictoor** [comment]
Fixed on npmjs. I guess in a few hours caches on yarnpkg.com will be updated. I will close this issue then

**Comment by alexvictoor** [comment]
Fixed now on yarnpkg.com
