### ISSUE TITLE
Log analyzer: Index Out Of Bounds Exception

### ISSUE THREAD

**Issue by jonathanstrong** [HdrHistogram/HdrHistogramJS#6]
I encountered an "out of bounds" exception trying to open a larger log file: (1 log per second for one hour). 

Chrome pointed me to this section of the code: 

```
            t.prototype.next = function() {
                for (; !this.exhaustedSubBuckets(); ) {
                    if (this.countAtThisValue = this.histogram.getCountAtIndex(this.currentIndex),
                    this.freshSubBucket && (this.totalCountToCurrentIndex += this.countAtThisValue,
                    this.totalValueToCurrentIndex += this.countAtThisValue * this.histogram.highestEquivalentValue(this.currentValueAtIndex),
                    this.freshSubBucket = !1),
                    this.reachedIterationLevel()) {
                        var t = this.getValueIteratedTo();
                        if (Object.assign(this.currentIterationValue, {
                            valueIteratedTo: t,
                            valueIteratedFrom: this.prevValueIteratedTo,
                            countAtValueIteratedTo: this.countAtThisValue,
                            countAddedInThisIterationStep: this.totalCountToCurrentIndex - this.totalCountToPrevIndex,
                            totalCountToThisValue: this.totalCountToCurrentIndex,
                            totalValueToThisValue: this.totalValueToCurrentIndex,
                            percentile: 100 * this.totalCountToCurrentIndex / this.arrayTotalCount,
                            percentileLevelIteratedTo: this.getPercentileIteratedTo()
                        }),
                        this.prevValueIteratedTo = t,
                        this.totalCountToPrevIndex = this.totalCountToCurrentIndex,
                        this.incrementIterationLevel(),
                        this.histogram.getTotalCount() !== this.savedHistogramTotalRawCount)
                            throw "Concurrent Modification Exception";
                        return this.currentIterationValue
                    }
                    this.incrementSubBucket()
                }
                throw "Index Out Of Bounds Exception"
            }
```

Other logs open fine that were generated by the same process, just for smaller amounts of time. 

Another anomaly, however, was that logs generated every 100ms and 1s opened fine, but a log generated every 200ms did not. In that case the error was saying the file was in the wrong format (not v2), however, it was in v2 format, and the java log analyzer opened it ok.

**Comment by alexvictoor** [comment]
Sorry for the late response.
About the first issue, how many recorded values are we talking about? 
For the second issue, could you send me a log sample (a few lines would be enough for me to investigate)
Thanks in advance

**Comment by jonathanstrong** [comment]
> how many recorded values

this was a spinning loop with average latency in the 10-100u range. one histogram was saved each second for an hour to the log. hopefully that is enough info. less formally, it seems like log files over 30m are going to be painful. there may not be any solution for this. 

> log sample

Don't have one handy atm, it's been a while - but will try to remember to post it if this happens again.

**Comment by alexvictoor** [comment]
You are right, there might not be any solution to handle very big files. 
I will increase the bucket size in the log parser app (from 2^32 to 2^53) in order to handle bigger log file. Unfortunately JavaScript does not have (yet) int64 numbers.  
Then the best I can do is to display an annoying error message  when the log file you are trying to analyse is too big...

**Comment by alexvictoor** [comment]
I have updated the logparser UI. You should be know be able too parse bigger log files. If a log file is still too big you should get warnings instead of an ugly stack trace.  
I am eager to get your feedback

**Comment by jonathanstrong** [comment]
actually I've only used this via the demo log viewer you have posted on github.io. Is that auto-updated to reflect the latest code? If not I can build it on my end.

**Comment by alexvictoor** [comment]
Indeed you can try again at https://hdrhistogram.github.io/HdrHistogramJSDemo/logparser.html

**Comment by jonathanstrong** [comment]
just opened a 62mb log (in ~23 seconds) without crashing, so definitely an improvement! Will report back with more thorough observations in a few days.

**Comment by jonathanstrong** [comment]
Follow-up on this: just successfully opened a 262mb log file (in 107 seconds, but still). Also love filtering by tag. thanks!
