### ISSUE TITLE
No more typings ?

### ISSUE THREAD

**Issue by jrakotoharisoa** [HdrHistogram/HdrHistogramJS#7]
Hi, 

All in the title... 
Little breaking for typescript project :)

Related to this commit : https://github.com/HdrHistogram/HdrHistogramJS/commit/e981d6cfa82a45b9df2b8c93e270981610b4021b#diff-e5e546dd2eb0351f813d63d1b39dbc48

Does definitions will be added again or should we define them ourselves now ?

**Comment by alexvictoor** [comment]
Sorry, I will take a look at that and release a patch

**Comment by alexvictoor** [comment]
Hello again
I have done a proper release. Please let me know if does the job on your side.
BTW if you do not use base64 encoding/decoding you can  now import HdrHistogram modules in a way that is compatible with tree shaking. 
Looking forward to get your feedback

**Comment by jrakotoharisoa** [comment]
Perfect, it works!

Thanks!
