### ISSUE TITLE
Package.json: "main" file doesn't exist

### ISSUE THREAD

**Issue by iest** [HdrHistogram/HdrHistogramJS#8]
The npm-published `v1.1.1` and `v1.1.0` don't have a valid `main` defined in package.json — it's pointing to an `./index.js` that doesn't exist.

In `v1.0.0` it pointed to `./dist/index.js`, which worked fine.

I only noticed as I was trying a fresh install of [autocannon](https://www.npmjs.com/package/autocannon) and saw an error that this module could not be found.

**Comment by alexvictoor** [comment]
Thanks for your feedback
I will take a look at that asap

**Comment by alexvictoor** [comment]
I have done a proper release.
Please let me know if there are still issues on your side.
BTW I did not knew autocannon, thanks!

**Comment by mcollina** [comment]
Hey @alexvictoor, thanks for doing this in JS! In autocannon we switched from https://github.com/mcollina/native-hdr-histogram to this library to remove the binary dependency!

**Comment by alexvictoor** [comment]
Thanks a lot @mcollina I appreciate!
BTW I have a few questions on the usage of HdrHistogram within autocannon. 
Where do you think is the best place du discuss about that? issues on autocannon ?

**Comment by mcollina** [comment]
Definitely, open an issue!
