### ISSUE TITLE
Properties failed when ran using fast-check instead of jsverify

### ISSUE THREAD

**Issue by dubzzz** [HdrHistogram/HdrHistogramJS#9]
Hello,

I ran the code of `HdrHistogramJS` against `fast-check` instead of `jsverify` while keeping the same properties and got an error in the test **Histogram percentile computation / should be accurate according to its significant figures**.

It failed with the following values:
```
{
"numbers":[1,273731571431425,9,7303993364561409,50,52,3751386548413441,4948256072812545,5491625052831745,37,6820721518315521,1574333073423361,4066896780404737,191939336521729,3913963619305473,26,2081131494695681,9,3073654167648769,4231391955982337,14,4088907194638337,7341523045991425,3242270122483201,22,8280565622691841,614007688308737,2269465752221185,52,6254379374366721,8631834766189569,5165852549298177,48,481559528507393,27,6095148584763393,6494913181050113,4146783990091777,4273437989623809,38,9,1,52,8268765467165697,4606074649282561,46,4408679411453953,4459593769963521,7,37,16,5090951553114113,19,33,51,50,8899584853504001,47,17,6408401069544449,3552700696961537,44,8,7898351911549441,7866448145080321,33,8199056252950017,27,8989833384898561,43,652641750147073,5595306040501249,11,8383692575115265,33,1867658007780353,18,8,35,46,2491766237109249,32,34,10,1,1841170092118017,4596838152228865,33,25,22,3229546595876865,25,49,788556722442241,5070788145520641,7348438610689025,6882393879584769,18,8700569757159425,2367777250240513],
"actual":8206027174371586,
"got":7349135720054783,
"relativeError":0.10442220530209534,
"variation":0.001,
"bitBucketSize":8
}
```

As I don't really know if this can be considered as a real issue, I have not push anything forward.
The migration commit to `fast-check` is available at https://github.com/dubzzz/HdrHistogramJS/commit/2d9443ecb8885d5ab6bc0c9b951d7a2df6425706

Please let me know if it is a real failure of the property.
If so I can give you an hand on fixing this problem if needed.

Regards,
Nicolas

**Comment by dubzzz** [comment]
Just to keep it clear:
The properties I run in both `jsverify` and `fast-check` are the ones of `Histogram.jsverify.spec.ts` with no modifications at all. They should be the same for both frameworks so I expect the two to either fail both or succeed both.

In the property which is failing I changed `arbData(100)` into `fc.array(fc.integer(1, Number.MAX_SAFE_INTEGER), 100, 100)` - *an array of size 100 containing only integers from 1 to MAX_SAFE_INTEGER* - which seems to be the same as `arbData(100)`. I kept the size of 100 fixed but I also have the issue if I let the framework play with the size (it fails with smaller sizes in those cases ~10)

**Comment by alexvictoor** [comment]
Hello Nicolas
Sorry I did not seen your issue before. Thanks a lot for this fast-check migration commit :) It is on my todo list from quite some time but you know... 
Anyway I will try to take a look at this issue, why it fails with fast-check, this week.
Cheers

Alex

**Comment by dubzzz** [comment]
Hello Alex,

No worries ;) I think that you should upgrade the version of my commit to take the latest fast-check, it provides better shrinking capabilities and is faster.

Feel free if you need help to troubleshoot the bug or adapt the test (you can use `{versbose: true}` in `fc.assert` for a more verbose output).

Regards,
Nicolas

**Comment by alexvictoor** [comment]
I have not upgraded fast-check yet but I have picked your commit!
The main issue was a bug in my 'reference implementation', the misleading behaviour of Array.sort()...
Thanks again for this issue!

**Comment by dubzzz** [comment]
Closing the issue as the problem as been fixed
